name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
repository: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/in_app_purchase
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 1.0.9+2
# Temporarily disable publishing until in_app_purchase_storekit is published.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: in_app_purchase_android
      ios:
        default_package: in_app_purchase_storekit

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.3.2

  in_app_purchase_android:
    git:
      url: https://github.com/qwertyway/plugins.git
      ref: master
      path: packages/in_app_purchase/in_app_purchase_android
  in_app_purchase_storekit:
    git:
      url: https://github.com/qwertyway/plugins.git
      ref: master
      path: packages/in_app_purchase/in_app_purchase_storekit

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.11.1
  plugin_platform_interface: ^2.1.2
  test: ^1.21.4
